---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets. DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        env:
          PYTHON_VERSION: "3.11"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        env:
          RUFF_VERSION: "0.4.3"
        run: |
          python -m pip install --upgrade pip
          pip install ruff==${{ env.RUFF_VERSION }}

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      # - name: flake8Lint
      #   run: docker-compose run --rm app sh -c "flake8"

      # Update output format to enable automatic inline annotations.
      # - name: Run Ruff
      #   run: ruff check --output-format=github .

      - name: Run ruff check
        env:
          USER: "1001"
        run: |
          docker-compose run --rm -u ${{ env.USER }} app sh -c "ruff check --output-format=github ."
